# Generated by Django 4.2.1 on 2023-05-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Бренд'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Продукты'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='imagev',
            new_name='image',
        ),
    ]
